### ISSUE TITLE
Action bars not working in 1.14

### ISSUE THREAD

**Issue by bloodmc** [KyoriPowered/text-extras#10]
Using text-extras 3.0.3 with Spigot 1.14.4, the TextAdapter sendActionBar method does nothing.

Issue is on following line

https://github.com/KyoriPowered/text-extras/blob/master/adapter-bukkit/src/main/java/net/kyori/text/adapter/bukkit/SpigotAdapter.java#L128

The method being used here has been deprecated in 1.14 and is no longer supported

https://hub.spigotmc.org/stash/projects/SPIGOT/repos/spigot/browse/Bukkit-Patches/0017-BungeeCord-Chat-API.patch#324-340

**Comment by me4502** [comment]
I'm experiencing the same issue on Paper 1.15.2, also using text-extras 3.0.3
